### ISSUE TITLE
The script does not work anymore

### ISSUE THREAD

**Issue by babyrage2021** [stevew2131BypassArchiveIs/Bypass-archive.is-Brave-Dissenter-ban#1]
It looks like archive updated it to not work anymore.

**Comment by stevew2131BypassArchiveIs** [comment]
@babyrage2021 Does the site redirect you to https://btdig.com/unsupported-browser ? If so, try using the updated README instructions which involve clearing your old site data and then let me know.

**Comment by stevew2131BypassArchiveIs** [comment]
@babyrage2021 Actually, you can just download version 3 and it should take care of this issue for you. Again, please let me know if the problem is solved or not.

**Comment by babyrage2021** [comment]
Installed V3 and it works. thank you.
