### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by HillBobby** [stevew2131BypassArchiveIs/Bypass-archive.is-Brave-Dissenter-ban#2]
Version 3. Going to archive.md dumps me to the captcha, doing the captcha then sends me to https://archive.md/unsupported-browser

I cleared cookies and site data, no fix.

**Comment by LordJABA** [comment]
Same here, just installed in brave on ubuntu 20.04 - It's redirecting me to "unsupported-browser" page

**Comment by stevew2131BypassArchiveIs** [comment]
The site is now double checking request headers. The latest update should fix that. Please open a new ticket if the issue persists again though.

**Comment by HillBobby** [comment]
Did you test it? Because it still doesn't work for me. And why are you liking your own posts?
